#!/bin/sh
MOD_DIR=""
FAULTY="faulty"
HELLO="hello"

case "$1" in
    start)
        echo "Loading kernel modules..."
        /usr/bin/scull_load
        /usr/bin/module_load $FAULTY
        modprobe $HELLO
        /usr/bin/aesdchar_load
        ;;
    stop)
        echo "Unloading kernel modules..."
        /usr/bin/scull_unload
        /usr/bin/module_unload $FAULTY
        rmmod $HELLO
        /usr/bin/aesdchar_unload
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
